function integer = StateToField(stateArray, state_mat)

% ids = false(size(state,2),1);
% for ii = 1:size(state,2)
%     ids(ii) = isequal(state(ii).buffer, [stateArray(1) stateArray(2)]) ...
%         && isequal(state(ii).mcs, stateArray(3)) ...
%         && isequal(state(ii).ack, [stateArray(4) stateArray(5)]) ...
%         && isequal(state(ii).channel, [stateArray(6) stateArray(7)]) ...
%         && isequal(state(ii).leftslot, stateArray(8));
% end

integer = find(ismember(state_mat, stateArray, 'rows'));

% integer = find(ids);
% 
% ids = false(size(state,2),1);
% for ii = 1:size(state,2)
%     ids(ii) = isequal(state(ii).buffer, [stateArray(1) stateArray(2)]) ...
%         && isequal(state(ii).mcs, [stateArray(3) stateArray(4)]) ...
%         && isequal(state(ii).ack, [stateArray(5) stateArray(6)]) ...
%         && isequal(state(ii).channel, [stateArray(7) stateArray(8)]) ...
%         && isequal(state(ii).leftslot, stateArray(9));
% end
% integer = find(ids);